/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao.funcionario;

import controle.GerenciadorDeBD;
import controle.GerenciadorDeFuncionario;
import javax.swing.JOptionPane;
import modeloBeans.funcionario.BeansFuncionario;
import modeloConection.ConexaoBD;
import modeloDAO.DaoFuncionario;

/**
 * Form de Entrada de Funcionario
 * @author geoavnef46
 */
public class FormEntradaFuncionario extends javax.swing.JFrame {

    private FormEntradaLogin novoLogin;
    private BeansFuncionario modelo = new BeansFuncionario();
    private GerenciadorDeFuncionario gFuncionario = new GerenciadorDeFuncionario();
    private GerenciadorDeBD DaoControl = new GerenciadorDeBD();
    private boolean flagLogin = false;

    /**
     * Creates new form FormEntradaFuncionario
     */
    public FormEntradaFuncionario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldNome = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldNomeRua = new javax.swing.JTextField();
        jFormattedTextFieldCPF = new javax.swing.JFormattedTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldNomeBairro = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldNomeRuaCidade = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jFormattedTextFieldNumero = new javax.swing.JFormattedTextField();
        jFormattedTextFieldTelefone01 = new javax.swing.JFormattedTextField();
        jLabel8 = new javax.swing.JLabel();
        jFormattedTextFieldTelefone02 = new javax.swing.JFormattedTextField();
        jButtonSalvar = new javax.swing.JButton();
        jButtonCriaLogin = new javax.swing.JButton();
        jButtonCancelar = new javax.swing.JButton();
        jComboBoxFuncao = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        jTextFieldCEP = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Novo Funcionario");
        getContentPane().setLayout(null);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("DejaVu Serif", 1, 12)); // NOI18N
        jLabel1.setText("Nome:");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(10, 40, 44, 15);

        jTextFieldNome.setMinimumSize(new java.awt.Dimension(4, 25));
        jPanel1.add(jTextFieldNome);
        jTextFieldNome.setBounds(60, 30, 686, 36);

        jLabel2.setFont(new java.awt.Font("DejaVu Serif", 1, 12)); // NOI18N
        jLabel2.setText("CPF:");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(10, 85, 31, 20);

        jTextFieldNomeRua.setMinimumSize(new java.awt.Dimension(4, 25));
        jPanel1.add(jTextFieldNomeRua);
        jTextFieldNomeRua.setBounds(260, 80, 486, 33);

        try {
            jFormattedTextFieldCPF.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###########")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFormattedTextFieldCPF.setToolTipText("Insira o CPF, apenas numeros!");
        jFormattedTextFieldCPF.setMinimumSize(new java.awt.Dimension(4, 25));
        jPanel1.add(jFormattedTextFieldCPF);
        jFormattedTextFieldCPF.setBounds(60, 80, 145, 29);

        jLabel3.setFont(new java.awt.Font("DejaVu Serif", 1, 12)); // NOI18N
        jLabel3.setText("Rua:");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(220, 90, 31, 15);

        jLabel4.setFont(new java.awt.Font("DejaVu Serif", 1, 12)); // NOI18N
        jLabel4.setText("Bairro");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(120, 130, 45, 15);

        jTextFieldNomeBairro.setMinimumSize(new java.awt.Dimension(4, 25));
        jPanel1.add(jTextFieldNomeBairro);
        jTextFieldNomeBairro.setBounds(180, 120, 145, 33);

        jLabel5.setFont(new java.awt.Font("DejaVu Serif", 1, 12)); // NOI18N
        jLabel5.setText("Cidade:");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(330, 130, 52, 15);

        jTextFieldNomeRuaCidade.setMinimumSize(new java.awt.Dimension(4, 25));
        jPanel1.add(jTextFieldNomeRuaCidade);
        jTextFieldNomeRuaCidade.setBounds(390, 120, 357, 37);

        jLabel6.setFont(new java.awt.Font("DejaVu Serif", 1, 12)); // NOI18N
        jLabel6.setText("Telefone Fixo:");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(10, 180, 97, 15);

        jLabel7.setFont(new java.awt.Font("DejaVu Serif", 1, 12)); // NOI18N
        jLabel7.setText("Nº:");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(10, 130, 21, 15);

        jFormattedTextFieldNumero.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#00"))));
        jFormattedTextFieldNumero.setMinimumSize(new java.awt.Dimension(4, 25));
        jPanel1.add(jFormattedTextFieldNumero);
        jFormattedTextFieldNumero.setBounds(60, 120, 39, 29);

        try {
            jFormattedTextFieldTelefone01.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#########")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFormattedTextFieldTelefone01.setMinimumSize(new java.awt.Dimension(4, 25));
        jPanel1.add(jFormattedTextFieldTelefone01);
        jFormattedTextFieldTelefone01.setBounds(120, 170, 130, 30);

        jLabel8.setFont(new java.awt.Font("DejaVu Serif", 1, 12)); // NOI18N
        jLabel8.setText("Celular:");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(50, 220, 55, 15);

        try {
            jFormattedTextFieldTelefone02.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#########")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFormattedTextFieldTelefone02.setMinimumSize(new java.awt.Dimension(4, 25));
        jFormattedTextFieldTelefone02.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormattedTextFieldTelefone02ActionPerformed(evt);
            }
        });
        jPanel1.add(jFormattedTextFieldTelefone02);
        jFormattedTextFieldTelefone02.setBounds(120, 210, 130, 32);

        jButtonSalvar.setFont(new java.awt.Font("DejaVu Serif", 1, 12)); // NOI18N
        jButtonSalvar.setText("Salvar");
        jButtonSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalvarActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonSalvar);
        jButtonSalvar.setBounds(620, 430, 109, 53);

        jButtonCriaLogin.setFont(new java.awt.Font("DejaVu Serif", 1, 12)); // NOI18N
        jButtonCriaLogin.setText("Permitir Acesso");
        jButtonCriaLogin.setToolTipText("Permitir acesso ao sistema ao funcionário");
        jButtonCriaLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCriaLoginActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonCriaLogin);
        jButtonCriaLogin.setBounds(310, 330, 169, 53);

        jButtonCancelar.setFont(new java.awt.Font("DejaVu Serif", 1, 12)); // NOI18N
        jButtonCancelar.setText("Cancelar");
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonCancelar);
        jButtonCancelar.setBounds(460, 430, 109, 53);

        jComboBoxFuncao.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione", "OP_PRODUCAO", "VENDEDOR", "GERENTE" }));
        jPanel1.add(jComboBoxFuncao);
        jComboBoxFuncao.setBounds(270, 280, 250, 25);

        jLabel9.setFont(new java.awt.Font("DejaVu Serif", 1, 12)); // NOI18N
        jLabel9.setText("Funcao:");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(360, 260, 54, 15);

        jTextFieldCEP.setMinimumSize(new java.awt.Dimension(4, 25));
        jPanel1.add(jTextFieldCEP);
        jTextFieldCEP.setBounds(390, 170, 145, 33);

        jLabel10.setFont(new java.awt.Font("DejaVu Serif", 1, 12)); // NOI18N
        jLabel10.setText("CEP:");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(350, 180, 40, 15);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(11, 18, 760, 504);

        setSize(new java.awt.Dimension(797, 566));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Event ao clicar o botão salvar; Emcopsula as entradas do novo funcionário
     * em um objeto do tipo BeansFuncionario
     *
     */
    private void jButtonSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalvarActionPerformed
        if (validarCampos() == true) {
            modelo.setNome(jTextFieldNome.getText());
            modelo.setBairro(jTextFieldNomeBairro.getText());
            modelo.setRua(jTextFieldNomeRua.getText());
            modelo.setCPF(jFormattedTextFieldCPF.getText());
            modelo.setCidade(jTextFieldNomeRuaCidade.getText());
            modelo.setNumero(Integer.parseInt(jFormattedTextFieldNumero.getText()));
            modelo.setCEP(jTextFieldCEP.getText());
            modelo.setTipoFunc((String) jComboBoxFuncao.getSelectedItem());
            modelo.setTelefone(Integer.parseInt(jFormattedTextFieldTelefone01.getText()));
            modelo.setTelefone2(Integer.parseInt(jFormattedTextFieldTelefone02.getText()));

            if (LoginCriado()) {
                BeansFuncionario model = novoLogin.retornaLogin();
                if (gFuncionario.confereAcesso(model)) {
                    flagLogin = true;
                    modelo.setNomeUsuario(model.getNomeUsuario());
                    modelo.setSenhaUsuario(model.getSenhaUsuario());
                    modelo.setTipoUsuario((String) jComboBoxFuncao.getSelectedItem());
                } else {
                    JOptionPane.showMessageDialog(rootPane, "Funcionario sem Login de acesso!");
                }
            }
            limparCampos();
            DaoControl.salvar(modelo);

            dispose();
            flagLogin = false;


    }//GEN-LAST:event_jButtonSalvarActionPerformed

    }

    public void limparCampos() {
        jTextFieldNome.setText("");
        jTextFieldNomeBairro.setText("");
        jTextFieldNomeRua.setText("");
        jTextFieldNomeRuaCidade.setText("");
        jFormattedTextFieldCPF.setText("");
        jFormattedTextFieldNumero.setText("");
        jFormattedTextFieldTelefone01.setText("");
        jFormattedTextFieldTelefone02.setText("");

    }

    private boolean validarCampos() {

        if (!jFormattedTextFieldCPF.getText().equals("") && !jTextFieldNome.getText().equals("")) {
            return true;
        } else {
            JOptionPane.showMessageDialog(rootPane, "Preencha os Dados do Funcionario!");
            return false;
        }
    }


    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed

        int resposta = 0;
        resposta = JOptionPane.showConfirmDialog(rootPane, "Deseja realmente Cancelar?", "Aviso", JOptionPane.YES_NO_OPTION);
        if (resposta == JOptionPane.YES_OPTION) {
            limparCampos();
            dispose();
        }

    }//GEN-LAST:event_jButtonCancelarActionPerformed

    private boolean LoginCriado() {

        return flagLogin;
    }
    private void jButtonCriaLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCriaLoginActionPerformed

        if (novoLogin == null) {
            novoLogin = new FormEntradaLogin(modelo);
            novoLogin.setVisible(true);
            novoLogin.setResizable(false);
        } else {
            novoLogin.setVisible(true);
            novoLogin.setResizable(false);
        }
    }//GEN-LAST:event_jButtonCriaLoginActionPerformed

    private void jFormattedTextFieldTelefone02ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormattedTextFieldTelefone02ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFormattedTextFieldTelefone02ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormEntradaFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormEntradaFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormEntradaFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormEntradaFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormEntradaFuncionario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonCriaLogin;
    private javax.swing.JButton jButtonSalvar;
    private javax.swing.JComboBox<String> jComboBoxFuncao;
    private javax.swing.JFormattedTextField jFormattedTextFieldCPF;
    private javax.swing.JFormattedTextField jFormattedTextFieldNumero;
    private javax.swing.JFormattedTextField jFormattedTextFieldTelefone01;
    private javax.swing.JFormattedTextField jFormattedTextFieldTelefone02;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextFieldCEP;
    private javax.swing.JTextField jTextFieldNome;
    private javax.swing.JTextField jTextFieldNomeBairro;
    private javax.swing.JTextField jTextFieldNomeRua;
    private javax.swing.JTextField jTextFieldNomeRuaCidade;
    // End of variables declaration//GEN-END:variables
}
