/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao.funcionario;

//import visao.produto.FormEntradaProduto;
//import visao.produto.PesquisaProduto;
//import visao.produto.FormVender;
import modeloBeans.funcionario.BeansFuncionario;
import visao.TelaLogin;
import visao.vendas.FormVender;
import visao.vendas.PesquisaMovel;
//import visao.funcionario.FormEntradaFuncionario;

/**
 * View principal do Funcionario do tipo Vendedor
 * @author geovanef46
 */
public class TelaPrincipalVendedor extends javax.swing.JFrame {

//    private FormEntradaFuncionario novoFuncionario;
    private PesquisaMovel novaPesquisa;
    private FormVender novaVenda;
     private BeansFuncionario funcionarioAtivo;
    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipalVendedor() {
        initComponents();
        jInternalFrameBemVindo.requestFocus();
    }

    public TelaPrincipalVendedor(BeansFuncionario funcionario ) {
          initComponents();
        //conecta.conexao();
        funcionarioAtivo = funcionario;
        jInternalFrameBemVindo.requestFocus();
        
        jLabelUsuario.setText("Conectado como  "+funcionario.getNome());
        
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jInternalFrameBemVindo = new javax.swing.JInternalFrame();
        jPanelInterno = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jButtonPesquisar = new javax.swing.JButton();
        jButtonVender = new javax.swing.JButton();
        jLabelTituloInterno = new javax.swing.JLabel();
        jLabelFundoTelaPrincipal = new javax.swing.JLabel();
        jLabelUsuario = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuIniciar = new javax.swing.JMenu();
        jMenuItemPesquisar = new javax.swing.JMenuItem();
        jMenuVender = new javax.swing.JMenuItem();
        jMenuRelatorios = new javax.swing.JMenu();
        jMenuFerramentas = new javax.swing.JMenu();
        jMenuItemBemVindo = new javax.swing.JMenuItem();
        jMenuSobre = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("VENDAS");
        setBackground(new java.awt.Color(255, 255, 255));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                FechouJanelaPrincipal(evt);
            }
        });
        getContentPane().setLayout(null);

        jInternalFrameBemVindo.setBackground(new java.awt.Color(220, 222, 228));
        jInternalFrameBemVindo.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(240, 240, 240), null));
        jInternalFrameBemVindo.setClosable(true);
        jInternalFrameBemVindo.setTitle("Bem - Vindo      Vendedor");
        jInternalFrameBemVindo.setFocusTraversalPolicyProvider(true);
        jInternalFrameBemVindo.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        try {
            jInternalFrameBemVindo.setSelected(true);
        } catch (java.beans.PropertyVetoException e1) {
            e1.printStackTrace();
        }
        jInternalFrameBemVindo.setVerifyInputWhenFocusTarget(false);
        jInternalFrameBemVindo.setVisible(true);
        jInternalFrameBemVindo.getContentPane().setLayout(null);

        jPanelInterno.setBackground(new java.awt.Color(229, 225, 240));
        jPanelInterno.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanelInterno.setLayout(null);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(255, 255, 255), null));
        jPanel2.setLayout(null);

        jLabel3.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(5, 5, 19));
        jLabel3.setText("Relatórios:");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(180, 10, 100, 30);

        jPanelInterno.add(jPanel2);
        jPanel2.setBounds(310, 10, 430, 320);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(255, 255, 255), null));
        jPanel3.setLayout(null);

        jButtonPesquisar.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        jButtonPesquisar.setForeground(new java.awt.Color(5, 5, 19));
        jButtonPesquisar.setText("Pesquisar");
        jButtonPesquisar.setToolTipText("Pesquisar um Movel para vender");
        jButtonPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPesquisarActionPerformed(evt);
            }
        });
        jPanel3.add(jButtonPesquisar);
        jButtonPesquisar.setBounds(50, 30, 180, 80);

        jButtonVender.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        jButtonVender.setForeground(new java.awt.Color(5, 5, 19));
        jButtonVender.setText("Vender");
        jButtonVender.setToolTipText("Vender um Movel");
        jButtonVender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVenderActionPerformed(evt);
            }
        });
        jPanel3.add(jButtonVender);
        jButtonVender.setBounds(50, 220, 180, 80);

        jPanelInterno.add(jPanel3);
        jPanel3.setBounds(10, 10, 280, 320);

        jInternalFrameBemVindo.getContentPane().add(jPanelInterno);
        jPanelInterno.setBounds(10, 40, 750, 340);

        jLabelTituloInterno.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        jLabelTituloInterno.setText("Movelaria Rocha");
        jInternalFrameBemVindo.getContentPane().add(jLabelTituloInterno);
        jLabelTituloInterno.setBounds(310, 10, 190, 30);

        getContentPane().add(jInternalFrameBemVindo);
        jInternalFrameBemVindo.setBounds(30, 50, 780, 420);

        jLabelFundoTelaPrincipal.setBackground(new java.awt.Color(255, 255, 255));
        jLabelFundoTelaPrincipal.setEnabled(false);
        getContentPane().add(jLabelFundoTelaPrincipal);
        jLabelFundoTelaPrincipal.setBounds(0, 0, 840, 500);

        jLabelUsuario.setText("Conectado como ");
        jLabelUsuario.setToolTipText("Usuário Ativo");
        jLabelUsuario.setEnabled(false);
        getContentPane().add(jLabelUsuario);
        jLabelUsuario.setBounds(490, 490, 320, 20);

        jMenuIniciar.setText("Iniciar");
        jMenuIniciar.setToolTipText("Encontrar um Móvel");

        jMenuItemPesquisar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_1, java.awt.event.InputEvent.ALT_MASK));
        jMenuItemPesquisar.setText("Pesquisar");
        jMenuItemPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemPesquisarActionPerformed(evt);
            }
        });
        jMenuIniciar.add(jMenuItemPesquisar);

        jMenuVender.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_2, java.awt.event.InputEvent.ALT_MASK));
        jMenuVender.setText("Vender");
        jMenuVender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuVenderActionPerformed(evt);
            }
        });
        jMenuIniciar.add(jMenuVender);

        jMenuBar1.add(jMenuIniciar);

        jMenuRelatorios.setText("Relatórios");
        jMenuBar1.add(jMenuRelatorios);

        jMenuFerramentas.setText("Ferramentas");

        jMenuItemBemVindo.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_1, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItemBemVindo.setText("Tela Bem-Vindo");
        jMenuItemBemVindo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemBemVindoActionPerformed(evt);
            }
        });
        jMenuFerramentas.add(jMenuItemBemVindo);

        jMenuBar1.add(jMenuFerramentas);

        jMenuSobre.setText("Sobre");
        jMenuSobre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuSobreMouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenuSobre);

        setJMenuBar(jMenuBar1);

        setSize(new java.awt.Dimension(858, 573));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemBemVindoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemBemVindoActionPerformed
        jInternalFrameBemVindo.requestFocus();
        jInternalFrameBemVindo.setVisible(true);
    }//GEN-LAST:event_jMenuItemBemVindoActionPerformed

    private void jMenuItemPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemPesquisarActionPerformed
        if (novaPesquisa == null) {
            novaPesquisa = new PesquisaMovel();
            novaPesquisa.setVisible(true);
            novaPesquisa.setResizable(false);
        }else{
            novaPesquisa.setVisible(true);
            novaPesquisa.setResizable(false);
        }
    }//GEN-LAST:event_jMenuItemPesquisarActionPerformed

    private void jButtonVenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVenderActionPerformed
        if (novaVenda == null) {
            novaVenda = new FormVender();
            novaVenda.setVisible(true);
            novaVenda.setResizable(false);
        }else{
            novaVenda.setVisible(true);
            novaVenda.setResizable(false);
        }
    }//GEN-LAST:event_jButtonVenderActionPerformed

    private void jButtonPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPesquisarActionPerformed
        if (novaPesquisa == null) {
            novaPesquisa = new PesquisaMovel();
            novaPesquisa.setVisible(true);
            novaPesquisa.setResizable(false);
        }else{
            novaPesquisa.setVisible(true);
            novaPesquisa.setResizable(false);
        }
    }//GEN-LAST:event_jButtonPesquisarActionPerformed

    private void FechouJanelaPrincipal(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_FechouJanelaPrincipal
        TelaLogin.tela.setVisible(true);
    }//GEN-LAST:event_FechouJanelaPrincipal

    private void jMenuSobreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuSobreMouseClicked

        
    }//GEN-LAST:event_jMenuSobreMouseClicked

    private void jMenuVenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuVenderActionPerformed
         if (novaVenda == null) {
            novaVenda = new FormVender();
            novaVenda.setVisible(true);
            novaVenda.setResizable(false);
        }else{
            novaVenda.setVisible(true);
            novaVenda.setResizable(false);
        }
    }//GEN-LAST:event_jMenuVenderActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipalVendedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipalVendedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipalVendedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipalVendedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipalVendedor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonPesquisar;
    private javax.swing.JButton jButtonVender;
    private javax.swing.JInternalFrame jInternalFrameBemVindo;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabelFundoTelaPrincipal;
    private javax.swing.JLabel jLabelTituloInterno;
    private javax.swing.JLabel jLabelUsuario;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuFerramentas;
    private javax.swing.JMenu jMenuIniciar;
    private javax.swing.JMenuItem jMenuItemBemVindo;
    private javax.swing.JMenuItem jMenuItemPesquisar;
    private javax.swing.JMenu jMenuRelatorios;
    private javax.swing.JMenu jMenuSobre;
    private javax.swing.JMenuItem jMenuVender;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanelInterno;
    // End of variables declaration//GEN-END:variables
}
