/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

import controle.GerenciadorDeLogin;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import modeloBeans.funcionario.BeansFuncionario;


/**
 * View principal de Login, para realizar autenticação no sistema
 * 
 * @author Geovanef46
 */
public class TelaLogin extends javax.swing.JFrame {
    public static JFrame tela;
    /**
     * Creates new form Tela_Login
     */
    public TelaLogin() {
        initComponents();
    }
    

    BeansFuncionario newUser= new BeansFuncionario();
    GerenciadorDeLogin gereciadorLogin;
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonCancelar = new javax.swing.JButton();
        jButtonAcessar = new javax.swing.JButton();
        jLabelSenha = new javax.swing.JLabel();
        jPasswordFieldSenha = new javax.swing.JPasswordField();
        jLabelLogin = new javax.swing.JLabel();
        jTextFieldLogin = new javax.swing.JTextField();
        jLabelFundoLogin = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Login");
        getContentPane().setLayout(null);

        jButtonCancelar.setText("SAIR");
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonCancelar);
        jButtonCancelar.setBounds(540, 200, 90, 30);

        jButtonAcessar.setText("ACESSAR");
        jButtonAcessar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAcessarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonAcessar);
        jButtonAcessar.setBounds(430, 200, 100, 30);

        jLabelSenha.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelSenha.setText("Senha");
        jLabelSenha.setToolTipText("");
        getContentPane().add(jLabelSenha);
        jLabelSenha.setBounds(370, 160, 50, 30);

        jPasswordFieldSenha.setToolTipText("Digite a sua senha");
        getContentPane().add(jPasswordFieldSenha);
        jPasswordFieldSenha.setBounds(430, 160, 200, 30);

        jLabelLogin.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelLogin.setText("Nome");
        jLabelLogin.setToolTipText("Nome de Usuário");
        getContentPane().add(jLabelLogin);
        jLabelLogin.setBounds(370, 130, 50, 30);

        jTextFieldLogin.setToolTipText("Digite o seu primeiro nome");
        jTextFieldLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldLoginActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldLogin);
        jTextFieldLogin.setBounds(430, 130, 200, 30);

        jLabelFundoLogin.setToolTipText("");
        jLabelFundoLogin.setName("Login"); // NOI18N
        getContentPane().add(jLabelFundoLogin);
        jLabelFundoLogin.setBounds(0, 0, 660, 310);

        setSize(new java.awt.Dimension(681, 356));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldLoginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldLoginActionPerformed

    private void jButtonAcessarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAcessarActionPerformed
      if(!campoVazio()){
          newUser.setNomeUsuario(jTextFieldLogin.getText());
          newUser.setSenhaUsuario(String.valueOf(jPasswordFieldSenha.getPassword()));
          GerenciadorDeLogin gereciadorLogin = GerenciadorDeLogin.getInstance();
          if(gereciadorLogin.fazerLogin(newUser) == true){
            
             dispose();
            
          }else{
              
          limparCampos();
          
          }
      }else{
          JOptionPane.showMessageDialog(rootPane, "Preencha os campos Nome e Senha Corretamente!");
      }
    }//GEN-LAST:event_jButtonAcessarActionPerformed
    
    private boolean campoVazio(){
     if(jPasswordFieldSenha.getPassword().length < 5 || jTextFieldLogin.getText().equals("")){
         jTextFieldLogin.requestFocus();
         return true;
     }
   
     return false;
        
    }
    
    private void limparCampos(){
        jTextFieldLogin.setText("");
        jPasswordFieldSenha.setText("");
        jTextFieldLogin.requestFocus();
    }
    
    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButtonCancelarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                       TelaLogin tela =  new TelaLogin();
               tela.setVisible(true);
               tela.setInstance(tela);
            }
        });
    }

       public void setInstance(JFrame tela){
           this.tela = tela;
       }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAcessar;
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JLabel jLabelFundoLogin;
    private javax.swing.JLabel jLabelLogin;
    private javax.swing.JLabel jLabelSenha;
    private javax.swing.JPasswordField jPasswordFieldSenha;
    private javax.swing.JTextField jTextFieldLogin;
    // End of variables declaration//GEN-END:variables
}
