/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

//import visao.relatorio.GerarRelatorio;
import modeloBeans.funcionario.BeansFuncionario;
import visao.producao.FormEntradaMovel;
//import visao.produto.PesquisaProduto;
//import visao.produto.FormVender;
import visao.producao.FormEntradaMP;
import visao.funcionario.FormEntradaFuncionario;
import visao.funcionario.PesquisaFuncionario;
import visao.producao.PesquisaMovel;

/**
 *  View Principal do Administrador
 * @author geovanef46
 */
public class TelaPrincipal extends javax.swing.JFrame {

    private FormEntradaMovel entradaMovel;
    private FormEntradaFuncionario novoFuncionario;
    private PesquisaMovel novaPesquisa;
//    private FormVender novaVenda;
//    private GerarRelatorio gerar;
    private FormEntradaMP entradaMP;
    private BeansFuncionario funcionarioAtivo;
    private PesquisaFuncionario novaPesquisaFunc;
 

    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
        initComponents();
        //conecta.conexao();
    }

    public TelaPrincipal(BeansFuncionario funcionario) {
          initComponents();
          funcionarioAtivo = funcionario;
          //conecta.conexao();
        
        jLabelUsuario.setText("Bem-Vindo   "+funcionario.GERENTE);
        
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.imageIco
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jInternalFrameBemVindo = new javax.swing.JInternalFrame();
        jLabelTituloInterno = new javax.swing.JLabel();
        jPanelInterno = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jButtonPesquisarFuncionario = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButtonNovoFuncionario = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jButtonGerarRelatorio = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabelFundoTelaPrincipal = new javax.swing.JLabel();
        jLabelUsuario = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuIniciar = new javax.swing.JMenu();
        jMenuItemNovoProduto = new javax.swing.JMenuItem();
        jMenuItemPesquisar = new javax.swing.JMenuItem();
        jMenuRelatorios = new javax.swing.JMenu();
        jMenuFerramentas = new javax.swing.JMenu();
        jMenuItemBemVindo = new javax.swing.JMenuItem();
        jMenuSobre = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("ADMINISTRADOR");
        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(800, 600));
        setMinimumSize(new java.awt.Dimension(800, 600));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                FechouJanelaPrincipal(evt);
            }
        });
        getContentPane().setLayout(null);

        jInternalFrameBemVindo.setBackground(new java.awt.Color(220, 222, 228));
        jInternalFrameBemVindo.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(240, 240, 240), null));
        jInternalFrameBemVindo.setClosable(true);
        jInternalFrameBemVindo.setTitle("Bem - Vindo");
        jInternalFrameBemVindo.setFocusTraversalPolicyProvider(true);
        jInternalFrameBemVindo.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        try {
            jInternalFrameBemVindo.setSelected(true);
        } catch (java.beans.PropertyVetoException e1) {
            e1.printStackTrace();
        }
        jInternalFrameBemVindo.setVisible(true);
        jInternalFrameBemVindo.getContentPane().setLayout(null);

        jLabelTituloInterno.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        jLabelTituloInterno.setText("Movelaria Rocha");
        jInternalFrameBemVindo.getContentPane().add(jLabelTituloInterno);
        jLabelTituloInterno.setBounds(310, 10, 190, 30);

        jPanelInterno.setBackground(new java.awt.Color(229, 225, 240));
        jPanelInterno.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanelInterno.setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(255, 255, 255), null));
        jPanel1.setLayout(null);

        jButtonPesquisarFuncionario.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        jButtonPesquisarFuncionario.setForeground(new java.awt.Color(5, 5, 19));
        jButtonPesquisarFuncionario.setText("Pesquisar");
        jButtonPesquisarFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPesquisarFuncionarioActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonPesquisarFuncionario);
        jButtonPesquisarFuncionario.setBounds(60, 240, 130, 50);

        jLabel1.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(5, 5, 19));
        jLabel1.setText("Funcionários:");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(70, 20, 110, 30);

        jButtonNovoFuncionario.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        jButtonNovoFuncionario.setForeground(new java.awt.Color(5, 5, 19));
        jButtonNovoFuncionario.setText("Novo");
        jButtonNovoFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNovoFuncionarioActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonNovoFuncionario);
        jButtonNovoFuncionario.setBounds(60, 60, 130, 50);

        jLabel3.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(5, 5, 19));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Crystal_Clear_app_Login_Manager.png"))); // NOI18N
        jLabel3.setText("  ");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(50, 80, 150, 190);

        jPanelInterno.add(jPanel1);
        jPanel1.setBounds(60, 10, 250, 320);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(255, 255, 255), null));
        jPanel2.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(5, 5, 19));
        jLabel2.setText("Relatórios:");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(90, 20, 100, 30);

        jButtonGerarRelatorio.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        jButtonGerarRelatorio.setForeground(new java.awt.Color(5, 5, 19));
        jButtonGerarRelatorio.setText("Gerar");
        jButtonGerarRelatorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGerarRelatorioActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonGerarRelatorio);
        jButtonGerarRelatorio.setBounds(70, 240, 120, 50);

        jLabel5.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(5, 5, 19));
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/relatorio.png"))); // NOI18N
        jPanel2.add(jLabel5);
        jLabel5.setBounds(60, 60, 150, 160);

        jPanelInterno.add(jPanel2);
        jPanel2.setBounds(440, 10, 250, 320);

        jInternalFrameBemVindo.getContentPane().add(jPanelInterno);
        jPanelInterno.setBounds(10, 40, 750, 340);

        getContentPane().add(jInternalFrameBemVindo);
        jInternalFrameBemVindo.setBounds(30, 50, 780, 420);
        try {
            jInternalFrameBemVindo.setIcon(true);
        } catch (java.beans.PropertyVetoException e1) {
            e1.printStackTrace();
        }

        jLabelFundoTelaPrincipal.setBackground(new java.awt.Color(255, 255, 255));
        jLabelFundoTelaPrincipal.setEnabled(false);
        getContentPane().add(jLabelFundoTelaPrincipal);
        jLabelFundoTelaPrincipal.setBounds(20, 10, 800, 500);

        jLabelUsuario.setText("Bem - Vindo");
        jLabelUsuario.setToolTipText("Usuário Ativo");
        jLabelUsuario.setEnabled(false);
        getContentPane().add(jLabelUsuario);
        jLabelUsuario.setBounds(620, 490, 200, 20);

        jMenuIniciar.setText("Iniciar");

        jMenuItemNovoProduto.setText("Novo Produto");
        jMenuItemNovoProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemNovoProdutoActionPerformed(evt);
            }
        });
        jMenuIniciar.add(jMenuItemNovoProduto);

        jMenuItemPesquisar.setText("Pesquisar");
        jMenuItemPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemPesquisarActionPerformed(evt);
            }
        });
        jMenuIniciar.add(jMenuItemPesquisar);

        jMenuBar1.add(jMenuIniciar);

        jMenuRelatorios.setText("Relatórios");
        jMenuBar1.add(jMenuRelatorios);

        jMenuFerramentas.setText("Ferramentas");

        jMenuItemBemVindo.setText("Tela Bem-Vindo");
        jMenuItemBemVindo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemBemVindoActionPerformed(evt);
            }
        });
        jMenuFerramentas.add(jMenuItemBemVindo);

        jMenuBar1.add(jMenuFerramentas);

        jMenuSobre.setText("Sobre");
        jMenuSobre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuSobreMouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenuSobre);

        setJMenuBar(jMenuBar1);

        setSize(new java.awt.Dimension(853, 575));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuSobreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuSobreMouseClicked
        //conecta.desconecta();//caso exista alguma conexão aberta
      
    }//GEN-LAST:event_jMenuSobreMouseClicked

    private void jMenuItemBemVindoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemBemVindoActionPerformed
        jInternalFrameBemVindo.setFocusable(true);
        jInternalFrameBemVindo.setVisible(true);
    }//GEN-LAST:event_jMenuItemBemVindoActionPerformed

    private void jMenuItemNovoProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemNovoProdutoActionPerformed
//         if (novaEntrada == null) {
//            novaEntrada = new FormEntradaMovel();
//            novaEntrada.setVisible(true);
//            novaEntrada.setResizable(false);
//        }else{
//            novaEntrada.setVisible(true);
//            novaEntrada.setResizable(false);  
//        }


    }//GEN-LAST:event_jMenuItemNovoProdutoActionPerformed

    private void jMenuItemPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemPesquisarActionPerformed
//        if (novaPesquisa == null) {
//            novaPesquisa = new PesquisaProduto();
//            novaPesquisa.setVisible(true);
//            novaPesquisa.setResizable(false);
//        }else{
//            novaPesquisa.setVisible(true);
//            novaPesquisa.setResizable(false);
//        }
    }//GEN-LAST:event_jMenuItemPesquisarActionPerformed

    private void jButtonPesquisarFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPesquisarFuncionarioActionPerformed
                if (novaPesquisaFunc == null) {
            novaPesquisaFunc = new PesquisaFuncionario();
            novaPesquisaFunc.setVisible(true);
            novaPesquisaFunc.setResizable(false);
        }else{
            novaPesquisaFunc.setVisible(true);
            novaPesquisaFunc.setResizable(false);
        }
    }//GEN-LAST:event_jButtonPesquisarFuncionarioActionPerformed

    private void jButtonNovoFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNovoFuncionarioActionPerformed
        if (novoFuncionario == null) {
            novoFuncionario = new FormEntradaFuncionario();
            novoFuncionario.setVisible(true);
            novoFuncionario.setResizable(false);
        }else{
            novoFuncionario.setVisible(true);
            novoFuncionario.setResizable(false);  
        }

    }//GEN-LAST:event_jButtonNovoFuncionarioActionPerformed

    private void jButtonGerarRelatorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGerarRelatorioActionPerformed
// 
//        if (gerar == null) {
//            gerar = new GerarRelatorio();
//            gerar.setVisible(true);
//            gerar.setResizable(false);
//        }else{
//            gerar.setVisible(true);
//            gerar.setResizable(false);
//        }
    }//GEN-LAST:event_jButtonGerarRelatorioActionPerformed

    private void FechouJanelaPrincipal(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_FechouJanelaPrincipal
        TelaLogin.tela.setVisible(true);
    }//GEN-LAST:event_FechouJanelaPrincipal

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonGerarRelatorio;
    private javax.swing.JButton jButtonNovoFuncionario;
    private javax.swing.JButton jButtonPesquisarFuncionario;
    private javax.swing.JInternalFrame jInternalFrameBemVindo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabelFundoTelaPrincipal;
    private javax.swing.JLabel jLabelTituloInterno;
    private javax.swing.JLabel jLabelUsuario;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuFerramentas;
    private javax.swing.JMenu jMenuIniciar;
    private javax.swing.JMenuItem jMenuItemBemVindo;
    private javax.swing.JMenuItem jMenuItemNovoProduto;
    private javax.swing.JMenuItem jMenuItemPesquisar;
    private javax.swing.JMenu jMenuRelatorios;
    private javax.swing.JMenu jMenuSobre;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanelInterno;
    // End of variables declaration//GEN-END:variables
}
